anct-cnum/portail-usager

- .github/workflows/destroy-application.yml
- .github/workflows/enable-cd.yml
- .github/workflows/list-applications.yml
Add dummy files for dispatch to appear in feature branch actions.
cf :  https://github.community/t/workflow-dispatch-workflow-not-showing-in-actions-tab/130088
> Dummy workflows for feature branch manual dispatch

- .github/workflows/destroy-application.yml
- .github/workflows/enable-cd.yml
- .github/workflows/feature-cd.yml
- angular.json
- package.json
- pages/index.html
- src/app/app.component.html
- yarn.lock
Add three CI workflows:
- Create an application for this branch on clever cloud and enable deployment on push. (manual dispatch)
- Full standard continous deployment workflow (lint / test / build / deploy | publish of a static site with coverage and bundle reports) (on push and manual dispatch)
- Destroy linked application on clevercloud for the selected branch. (manual dispatch)
> Creation, Suppression et déploiement continu

- src/features/cartography/core/repositories/coordinates.repository.ts
- src/features/cartography/core/repositories/index.ts
- src/features/cartography/infrastructure/configuration/modules/cartography.feature.module.ts
- src/features/cartography/infrastructure/data/models/coordinates.transfer-mapper.ts
- src/features/cartography/infrastructure/data/rest/cnfs/cnfs.rest.ts
- src/features/cartography/infrastructure/data/rest/coordinates/coordinates.rest.ts
- src/features/cartography/infrastructure/data/rest/coordinates/index.ts
- src/features/cartography/infrastructure/presentation/components/leaflet-map/leaflet-map.component.html
- src/features/cartography/infrastructure/presentation/components/leaflet-map/leaflet-map.component.ts
- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.page.html
- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.page.spec.ts
- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.page.ts
- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.presenter.ts
- src/features/cartography/use-cases/geocode-address/geocode-address.use-case.ts
- src/features/cartography/use-cases/list-cnfs/list-cnfs-positions.use-case.ts
> Minimal address geocoding

- src/features/cartography/infrastructure/presentation/components/leaflet-map/leaflet-map.component.html
- src/features/cartography/infrastructure/presentation/components/leaflet-map/leaflet-map.component.ts
- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.page.html
- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.page.ts
Au final j'utilise directtement la Geolocation api car le map.locate() de leaflet ne réponds pas au besoin de manière pratique.
> Feat: Autolocate usager 

- package.json
- src/app/interceptors/api-rewrite-url.interceptor.spec.ts
- src/app/interceptors/api-rewrite-url.interceptor.ts
- src/app/interceptors/errors/index.ts
- src/app/interceptors/errors/not-in-available-apis.error.ts
- src/app/modules/app.module.ts
- src/app/tokens/api/api.configuration.ts
- src/app/tokens/api/apis.token.ts
- src/app/tokens/api/index.ts
- src/app/tokens/index.ts
- src/environments/environment.model.ts
- src/environments/environment.production.ts
- src/environments/environment.ts
- src/features/cartography/infrastructure/configuration/modules/cartography.feature.module.ts
- src/features/cartography/infrastructure/configuration/tokens/marker/markers.token.ts
- src/features/cartography/infrastructure/data/rest/cnfs/cnfs.rest.ts
- src/features/cartography/infrastructure/data/rest/coordinates/coordinates.rest.ts
- src/features/cartography/infrastructure/presentation/components/leaflet-map/leaflet-map.component.ts
Permet l'ajout et management de divers domaines api en fonction de l’environnement.
> Better url management and http interceptor

- src/features/cartography/infrastructure/presentation/components/leaflet-map/leaflet-map.component.ts
> Centrer la carte sur un point d'intérêt

- .stylelintrc.json
- src/features/cartography/infrastructure/configuration/tokens/marker/markers.factories.ts
- src/features/cartography/infrastructure/configuration/tokens/marker/markers.token.ts
- src/features/cartography/infrastructure/presentation/components/leaflet-map/leaflet-map.component.ts
- src/features/cartography/infrastructure/presentation/models/cnfs/cnfs.presentation-mapper.ts
- src/features/cartography/infrastructure/presentation/models/cnfs/cnfs.presentation-model.ts
- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.page.ts
- src/features/cartography/infrastructure/presentation/pipes/add-usager-marker.pipe.spec.ts
- src/features/cartography/infrastructure/presentation/pipes/add-usager-marker.pipe.ts
- src/features/cartography/infrastructure/presentation/pipes/view-culling.pipe.spec.ts
- src/features/cartography/infrastructure/presentation/pipes/view-culling.pipe.ts
- src/features/cartography/infrastructure/presentation/services/cluster.service.ts
- src/styles.scss
Ajout des nombres sur les clusters.
Testez la démo [ici](https://app-83601235-81d9-4c2a-abb9-c9a3ed62ea0d.cleverapps.io/cartographie)
> Ajout du nombre de conseillers sur les clusters

- src/features/cartography/infrastructure/configuration/tokens/marker/index.ts
- src/features/cartography/infrastructure/configuration/tokens/marker/marker.configuration.ts
- src/features/cartography/infrastructure/configuration/tokens/marker/markers.configuration.ts
- src/features/cartography/infrastructure/configuration/tokens/marker/markers.token.ts
- src/features/cartography/infrastructure/presentation/components/leaflet-map/leaflet-map.component.ts
- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.page.ts
Testez la démo [ici](https://app-5adb45cf-bc4b-44f5-a24d-b4b18b239303.cleverapps.io)
La CI est passé en vrai je l'ai juste run en manuel : https://github.com/anct-cnum/portail-usager/actions/runs/1535003281
> Ajout rechargement carte après le chargement des données

- src/features/cartography/infrastructure/presentation/components/leaflet-map/leaflet-map.component.ts
- src/features/cartography/infrastructure/presentation/models/cnfs/cnfs.presentation-model.ts
- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.page.html
- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.page.ts
Add the necessary listener on leaflet marker and flatpass to angular.
It is not necessary to off() the listener on layer destroy as leaflet removeLayer() manages it.
> Exploratoire : Accès à l’événement clic et propriétés d'un marqueur

- .github/workflows/production-cd.yml
- .github/workflows/staging-cd.yml
- package.json
- yarn.lock
Staging and production workflows.
> Feat staging and production workflows

- .github/workflows/production-cd.yml
- .github/workflows/staging-cd.yml
- package.json
- yarn.lock
Staging and production continuous deployment workflows
> Staging and production continuous deployment workflows

- src/app/components/header/header.component.html
- src/app/components/header/header.component.spec.ts
- src/app/components/index.ts
- src/app/components/main-navigation/index.ts
- src/app/components/main-navigation/menu/menu.component.html
- src/app/components/main-navigation/menu/menu.component.spec.ts
- src/app/components/main-navigation/menu/menu.component.ts
- src/app/modules/app.module.ts
- src/app/pipes/index.ts
- src/app/pipes/slugify/slugify.pipe.spec.ts
- src/app/pipes/slugify/slugify.pipe.ts
- src/app/test-doubles/components/main-navigation/menu/menu.component.stub.ts
- src/app/test-doubles/index.ts
- src/app/test-doubles/modules/app.testing.module.ts
- src/app/test-doubles/pipes/slugify/slugify.pipe.stub.ts
- src/styles/fixes/main.scss
- src/styles/main.scss
[Demo link](https://app-aa08a472-5458-435c-8621-a781c833c840.cleverapps.io/)
> add header navigation main menu

- src/features/cartography/infrastructure/configuration/tokens/marker/markers.factories.ts
- src/features/cartography/infrastructure/presentation/components/leaflet-map/leaflet-map.component.ts
- src/features/cartography/infrastructure/presentation/components/permanence-map/permanence-map.component.ts
[Demo link](https://app-f9c4b48b-a9ad-4c59-a8ac-0d1c842a4c35.cleverapps.io/)
> Affichage du nom de la structure dans une popup au clic d'un pin sur la carte

- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.page.ts
- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.presenter.spec.ts
- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.presenter.ts
Fix du bug
[Testez la démo ici](https://app-75101d9e-6101-4c01-b048-760ba54383ab.cleverapps.io/)
> Bugfix: En cas de recherche d'adresse invalide la fonction de recherche est bloquée

- .github/workflows/feature-cd.yml
crée ou met à jour automatiquement l'instance clevercloud de démo si la branche est nommée
selon les patterns
feature/* 
fix/*
> DevOps QOL : Automatiser la création / déploiement des application de démo branches de feature et fix

- .github/workflows/destroy-application.yml
Reverts anct-cnum/portail-usager#58
> Revert "test-ci"

- .github/workflows/destroy-application.yml
##Description
Merge for delete workflow to be active
> WIP destroy a deployed application on branch deleted

- .github/workflows/destroy-application.yml
Supprime automatiquement l'instance de démo sur clevercloud à la suppression d'une branches qui suit le pattern
feature/*
fix/*
J'ai configuré le repo pour supprimer aussi la branche au merge sur main.
> DevOps QOL: Destroy clevercloud demo application on feature or fix branch deletion

- src/app/components/footer/footer.component.html
> remove cookie link

- .github/workflows/build-angular.reusable.yml
- .github/workflows/deploy-static-application-to-clevercloud.reusable.yml
- .github/workflows/destroy-feature-or-fix-demo-application.yml
- .github/workflows/feature-or-fix-continuous-deployment.yml
- .github/workflows/notify-deployment-mattermost.reusable.yml
- .github/workflows/production-continuous-deployment.yml
- .github/workflows/staging-continuous-deployment.yml
- Corrige le nom des cibles pour la recette et production
- Ajoute un retry pour la première création de l'application sur clevercloud (le service met parfois un peu de temps à être disponible)
- Notification mattermost avec lien de démo :)
> DevOps: Fix/workflows small fixes

- angular.json
- src/scripts/tracker.js
Ajout du tracker Matomo
http://app-1a982c7c-ca27-425f-bcd3-ebc6c2d2b12a.cleverapps.io/
> Ajout tracker matomo

- src/features/cartography/infrastructure/presentation/components/cnfs-details/cnfs-details.component.html
- src/features/cartography/infrastructure/presentation/components/incomplete-data-notice/incomplete-data-notice.component.html
Please check if your PR fulfills the following requirements:
[Issue link](PASTE_LINK_HERE)
[Demo link](PASTE_LINK_HERE)
-
-
-
> MEP : Fix textes

- src/features/cartography/infrastructure/presentation/components/incomplete-data-notice/incomplete-data-notice.component.html
- src/features/cartography/infrastructure/presentation/components/switch-map-list/switch-map-list.component.html
- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.page.html
Display incomplete data notice full width to match [new design](https://www.figma.com/file/dwJ2A6XqoF6F6czTdtLy1r/CARTO---Pop-up-INFORMATION-(Copy)?node-id=0%3A1)
[Demo](https://app-0f7d5ffd-bb1c-4e1a-95b0-39a3d7a1fc46.cleverapps.io/)
> set missing data message full width on every views

- src/features/cartography/infrastructure/presentation/components/address-geolocation/address-geolocation.component.html
- src/features/cartography/infrastructure/presentation/components/address-geolocation/address-geolocation.component.ts
- src/features/cartography/infrastructure/presentation/pages/cnfs-list/cnfs-list.page.html
remove label and large class on search bar when structure list is not empty
[Demo](https://app-ba6ee26d-6722-410a-a9cd-98a7f3a546a0.cleverapps.io/)
> remove label and large class on search bar when structure list is not empty

- src/features/cartography/infrastructure/configuration/tokens/marker/markers.factories.ts
- src/features/cartography/infrastructure/presentation/components/cnfs-list/cnfs-list.component.html
- src/features/cartography/infrastructure/presentation/components/cnfs-list/cnfs-list.component.ts
- src/features/cartography/infrastructure/presentation/components/permanence-map/permanence-map.component.html
- src/features/cartography/infrastructure/presentation/components/permanence-map/permanence-map.component.ts
- src/features/cartography/infrastructure/presentation/directives/leaflet-marker/leaflet-map-marker.directive.ts
- src/features/cartography/infrastructure/presentation/models/cnfs-permanence/cnfs-permanence.presentation.ts
- src/features/cartography/infrastructure/presentation/models/markers/markers.presentation.ts
- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.layout.html
- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.layout.ts
- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.presenter.spec.ts
- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.presenter.ts
- src/features/cartography/infrastructure/presentation/pages/cnfs-details/cnfs-details.page.ts
- src/features/cartography/infrastructure/presentation/pages/cnfs-list/cnfs-list.page.html
- src/features/cartography/infrastructure/presentation/pages/cnfs-list/cnfs-list.page.ts
- Display cnfs marker with hint state on structure element hover in structure list
[Demo](https://app-5bf88710-2069-4a2d-ac3c-3b83f360861e.cleverapps.io/)
> marker highlight can have focus and hint values instead of boolean

- src/features/cartography/infrastructure/presentation/components/cnfs-list/cnfs-list.component.ts
- Change scroll in cnfs list component to trigger on  structures list update
[Demo](https://app-2fa0513b-e9d4-4ea2-871f-c68d6498c2d2.cleverapps.io/61304c94838083d339caa13f)
> scroll to cnfs list item on cnfs list update

- .github/workflows/feature-or-fix-continuous-deployment.yml
- angular.json
- src/environments/environment.branch.ts
- src/features/cartography/infrastructure/presentation/components/cnfs-list/cnfs-list.component.html
Fix structure label alignement
[Demo]()
> fix structure label alignment

- src/features/cartography/infrastructure/presentation/components/cnfs-details/cnfs-details.component.html
- src/features/cartography/infrastructure/presentation/components/cnfs-list/cnfs-list.component.html
Add title on aidants connect label
> add title on aidants connect label

- src/features/cartography/infrastructure/presentation/models/structure/structure-opening.helper.ts
- src/features/cartography/infrastructure/presentation/pages/cartography/cartography.presenter.spec.ts
> fix: add hook to avoid parsing opening hours with strating time but no ending time
